"""add_llm_chat_sessions

Revision ID: 7c926fe0db38
Revises: 7974e835d07f
Create Date: 2026-07-20 09:07:14.856579

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c926fe0db38'
down_revision: str | Sequence[str] | None = '7974e835d07f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_chat_sessions_id'), 'llm_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_llm_chat_sessions_project_id'), 'llm_chat_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_chat_sessions_user_id'), 'llm_chat_sessions', ['user_id'], unique=False)
    op.create_table('llm_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['llm_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_chat_messages_id'), 'llm_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_llm_chat_messages_session_id'), 'llm_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_chat_messages_session_id'), table_name='llm_chat_messages')
    op.drop_index(op.f('ix_llm_chat_messages_id'), table_name='llm_chat_messages')
    op.drop_table('llm_chat_messages')
    op.drop_index(op.f('ix_llm_chat_sessions_user_id'), table_name='llm_chat_sessions')
    op.drop_index(op.f('ix_llm_chat_sessions_project_id'), table_name='llm_chat_sessions')
    op.drop_index(op.f('ix_llm_chat_sessions_id'), table_name='llm_chat_sessions')
    op.drop_table('llm_chat_sessions')
    # ### end Alembic commands ###
